//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionAndAnswerMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistration
    {
        public int UserId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Username { get; set; }
        public string Pwd { get; set; }
        public string Confirmpassword { get; set; }
        public string Email { get; set; }
        public Nullable<int> YearsOfExperience { get; set; }
        public string Technology { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
